name: Deploy Backend Ventas to AWS ECR

on:
  push:
    branches: [ "deploy" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del codigo
      uses: actions/checkout@v3

    - name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Login en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Construir, etiquetar y subir Imagen a ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: back-ventas
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Login en Amazon ECR para obtener URL
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Obtener ID de la Instancia Web por su Tag
      id: get-instance
      run: |
        INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=web" "Name=instance-state-name,Values=running" --query "Reservations[*].Instances[*].InstanceId" --output text)
        echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_OUTPUT

    - name: Desplegar en EC2 via AWS Systems Manager (SSM)
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        aws ssm send-command \
          --instance-ids "${{ steps.get-instance.outputs.INSTANCE_ID }}" \
          --document-name "AWS-RunShellScript" \
          --comment "Desplegando Backend de Ventas" \
          --parameters 'commands=[
            "export AWS_ACCESS_KEY_ID='"${{ secrets.AWS_ACCESS_KEY_ID }}"'",
            "export AWS_SECRET_ACCESS_KEY='"${{ secrets.AWS_SECRET_ACCESS_KEY }}"'",
            "export AWS_SESSION_TOKEN='"${{ secrets.AWS_SESSION_TOKEN }}"'",
            "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin '"$ECR_REGISTRY"'",
            "docker pull '"$ECR_REGISTRY"'/back-ventas:latest",
            "docker stop back-ventas || true",
            "docker rm back-ventas || true",
            "docker run -d --name back-ventas -p 8080:8080 '"$ECR_REGISTRY"'/back-ventas:latest"
          ]' \
          --region us-east-1